steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/whisperx-api', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/whisperx-api'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'whisperx-api',
        '--image', 'gcr.io/$PROJECT_ID/whisperx-api',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--cpu', '2',
        '--memory', '4Gi',
        '--port', '8080',
        '--timeout', '900s',
        '--gpu', 'l4'  
      ]
timeout: 2400s
