steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/transcript-tool-472219/whisperx-repo/whisperx',
      '.'
    ]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "whisperx-service",
        "--image", "us-central1-docker.pkg.dev/transcript-tool-472219/whisperx-repo/whisperx",
        "--region", "us-central1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--memory", "16Gi",
        "--cpu", "4",
        "--gpu", "1"
      ]

images:
  - 'us-central1-docker.pkg.dev/transcript-tool-472219/whisperx-repo/whisperx'

timeout: 2400s
