FROM us-central1-docker.pkg.dev/transcript-tool-472219/whisperx-repo/base:latest

WORKDIR /app

# Copy code
COPY . .

# Setting HF token at build or runtime
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]