FROM us-central1-docker.pkg.dev/transcript-tool-472219/whisperx-repo/base:latest

WORKDIR /app

# Copy only code (requirements are already baked into base)
COPY . .

EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]